// src/lib/components/News.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { supabase } from '$lib/supabase';
  import { Newspaper, ChevronUp, ChevronLeft, ChevronRight, CalendarDays, MapPin, User, Loader2 } from 'lucide-svelte';
  import { fade, slide, fly } from 'svelte/transition';
  import { cn } from '$lib/utils';
  import placeholderData from '$lib/placeholder-images.json';

  // State
  let news = $state<any[]>([]);
  let isLoading = $state(true);
  let page = $state(1);
  let itemsPerPage = 2;
  let openItem = $state<string | null>(null);
  let isHovering = $state(false);
  let animationDirection = $state<'left' | 'right' | null>(null);

  // Derived
  const totalPages = $derived(news.length > 0 ? Math.ceil(news.length / itemsPerPage) : 0);
  const currentNews = $derived(news.slice((page - 1) * itemsPerPage, page * itemsPerPage));

  // Autoplay
  let autoplayTimer: any;

  async function fetchNews() {
    isLoading = true;
    try {
      const { data, error } = await supabase
        .from('news_items')
        .select('*')
        .order('date', { ascending: false });
      
      if (error) {
        console.error('Supabase query error:', error);
      }
      
      if (data) {
        news = data.map(item => {
          let url = item.imageUrl || '';
          if (item.imageId) {
            const placeholder = placeholderData.placeholderImages.find(p => p.id === item.imageId);
            if (placeholder) {
              url = placeholder.imageUrl;
            }
          }
          return { ...item, imageUrl: url };
        });
      }
    } catch (e) {
      console.error('Supabase fetch error:', e);
    } finally {
      isLoading = false;
    }
  }

  function handlePageChange(newPage: number) {
    if (totalPages <= 1) return;
    
    let target = newPage;
    if (target > totalPages) target = 1;
    if (target < 1) target = totalPages;
    
    if (target === page) return;

    animationDirection = target > page ? 'left' : 'right';
    page = target;
    
    setTimeout(() => {
        animationDirection = null;
    }, 500);
  }

  function startAutoplay() {
    stopAutoplay();
    if (!isHovering && !openItem && totalPages > 1) {
      autoplayTimer = setInterval(() => {
        handlePageChange(page + 1);
      }, 5000);
    }
  }

  function stopAutoplay() {
    if (autoplayTimer) clearInterval(autoplayTimer);
  }

  onMount(() => {
    fetchNews();
  });

  onDestroy(() => {
    stopAutoplay();
  });

  $effect(() => {
    if (!isHovering && !openItem && totalPages > 1) {
      startAutoplay();
    } else {
      stopAutoplay();
    }
  });

  function formatDate(dateStr: string) {
    if (!dateStr) return 'N/A';
    try {
      const d = new Date(dateStr);
      if (isNaN(d.getTime())) return dateStr;
      return new Intl.DateTimeFormat('en-US', {
        month: 'long', day: 'numeric', year: 'numeric'
      }).format(d);
    } catch (e) {
      return dateStr;
    }
  }
</script>

<section 
  id="news" 
  class="py-20 sm:py-32 bg-card/10 overflow-hidden"
  onmouseenter={() => isHovering = true}
  onmouseleave={() => isHovering = false}
>
  <div class="container mx-auto px-6 max-w-6xl">
    <div class="mb-16 text-center">
      <h2 class="text-3xl sm:text-4xl font-bold font-slab text-primary mb-4 flex items-center justify-center gap-3">
        <Newspaper class="w-8 h-8" />
        Latest News
      </h2>
    </div>

    {#if isLoading}
      <div class="flex flex-col items-center justify-center py-20 gap-4">
        <Loader2 class="w-10 h-10 animate-spin text-primary" />
        <p class="text-sm font-mono uppercase tracking-widest text-muted-foreground">Synchronizing Archives...</p>
      </div>
    {:else if news.length === 0}
      <div class="text-center bg-card/40 border border-border/50 p-12 rounded-2xl">
        <p class="text-muted-foreground mb-4">No transmission records available at this time.</p>
      </div>
    {:else}
      <div class="relative min-h-[400px] grid grid-cols-1 grid-rows-1">
        {#key page}
          <div 
            class="space-y-6 col-start-1 row-start-1 w-full"
            in:fly={{ x: animationDirection === 'left' ? 50 : -50, duration: 500 }}
            out:fly={{ x: animationDirection === 'left' ? -50 : 50, duration: 300 }}
          >
            {#each currentNews as item}
              <div class="group bg-card border border-border/50 rounded-xl shadow-lg hover:shadow-primary/5 transition-all duration-500 overflow-hidden">
                <div class="relative">
                  {#if item.imageUrl}
                    <button 
                      class={cn(
                        "absolute z-20 rounded-lg overflow-hidden transition-all duration-700 ease-in-out cursor-pointer",
                        openItem === item.id 
                          ? "top-24 left-6 right-6 w-[calc(100%-3rem)] aspect-video shadow-2xl" 
                          : "top-6 left-6 w-24 aspect-[4/3] shadow-md group-hover:scale-105"
                      )}
                      onclick={() => openItem = openItem === item.id ? null : item.id}
                    >
                      <img src={item.imageUrl} alt={item.title} class="w-full h-full object-cover" />
                    </button>
                  {/if}

                  <button 
                    class={cn(
                      "w-full text-left p-6 transition-all duration-700 ease-in-out flex items-center justify-between",
                      item.imageUrl && (openItem !== item.id ? "pl-36" : "pb-6")
                    )}
                    onclick={() => openItem = openItem === item.id ? null : item.id}
                  >
                    <div class="flex-1">
                      <h3 class={cn("font-slab text-xl transition-colors", openItem === item.id ? "text-primary" : "text-foreground group-hover:text-primary")}>
                        {@html item.title}
                      </h3>
                      <div class="flex flex-wrap items-center gap-4 mt-3 text-xs font-mono text-muted-foreground">
                        <div class="flex items-center gap-1.5"><CalendarDays class="w-3.5 h-3.5 text-primary" /><span>{formatDate(item.date)}</span></div>
                        {#if item.location}<div class="flex items-center gap-1.5"><MapPin class="w-3.5 h-3.5" /><span>{item.location}</span></div>{/if}
                        {#if item.author}<div class="flex items-center gap-1.5"><User class="w-3.5 h-3.5" /><span>By {item.author}</span></div>{/if}
                      </div>
                    </div>
                    <ChevronUp class={cn("w-5 h-5 transition-transform duration-500", openItem !== item.id && "rotate-180")} />
                  </button>

                  {#if openItem === item.id}
                    <div class="px-6 pb-8" transition:slide={{ duration: 500 }}>
                      <div class={cn(item.imageUrl && "mt-[calc(56.25%_+_1rem)]")}>
                        <div class="pt-6 border-t border-border/50 text-muted-foreground text-justify leading-relaxed" in:fade={{ delay: 300 }}>
                          {@html item.content}
                        </div>
                      </div>
                    </div>
                  {/if}
                </div>
              </div>
            {/each}
          </div>
        {/key}
      </div>

      {#if totalPages > 1}
        <div class="flex justify-center items-center mt-12 gap-2">
          <button class="w-10 h-10 rounded-full border border-border/50 flex items-center justify-center hover:bg-gradient-soft hover:text-primary-foreground transition-colors disabled:opacity-30" onclick={() => handlePageChange(page - 1)}><ChevronLeft class="w-5 h-5" /></button>
          {#each Array.from({ length: totalPages }) as _, i}
            <button class={cn("w-10 h-10 rounded-full font-mono text-sm transition-all", page === i + 1 ? "bg-gradient-soft text-primary-foreground shadow-lg shadow-primary/20" : "border border-border/50 hover:border-primary/50")} onclick={() => handlePageChange(i + 1)}>{i + 1}</button>
          {/each}
          <button class="w-10 h-10 rounded-full border border-border/50 flex items-center justify-center hover:bg-gradient-soft hover:text-primary-foreground transition-colors disabled:opacity-30" onclick={() => handlePageChange(page + 1)}><ChevronRight class="w-5 h-5" /></button>
        </div>
      {/if}
    {/if}
  </div>
</section>

// src/components/sections/News.tsx
"use client";

import React, { useState, useEffect, useRef } from "react";
import { NewsItem as NewsItemType } from '@/lib/types';
import { PlaceHolderImages } from "@/lib/placeholder-images";
import Image from "next/image";
import { Accordion, AccordionContent, AccordionItem } from "@/components/ui/accordion";
import { Newspaper, ChevronUp, ChevronLeft, ChevronRight, CalendarDays, MapPin, User } from "lucide-react";
import * as AccordionPrimitive from "@radix-ui/react-accordion";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { useCollection } from '@/firebase/firestore/use-collection';
import { useFirestore, useMemoFirebase } from '@/firebase';
import { collection, query, orderBy } from 'firebase/firestore';
import { Skeleton } from "@/components/ui/skeleton";
import Link from "next/link";
import { format } from 'date-fns';

export function News() {
  const firestore = useFirestore();
  const newsCollectionQuery = useMemoFirebase(() => {
    if (!firestore) return null;
    return query(collection(firestore, 'news_items'), orderBy('date', 'desc'));
  }, [firestore]);

  const { data: news, isLoading } = useCollection<NewsItemType>(newsCollectionQuery);

  const itemsPerPage = 2;
  const totalPages = news ? Math.ceil(news.length / itemsPerPage) : 0;
  const autoplayInterval = 5000;

  const [page, setPage] = useState(1);
  const [animationClass, setAnimationClass] = useState("");
  const [isPaginating, setIsPaginating] = useState(false);
  const [isHovering, setIsHovering] = useState(false);
  const [openItem, setOpenItem] = useState<string | undefined>();

  const timerRef = useRef<NodeJS.Timeout | null>(null);

  const startIndex = (page - 1) * itemsPerPage;
  const currentNews = news ? news.slice(startIndex, startIndex + itemsPerPage) : [];

  const handlePageChange = (newPage: number) => {
    if (isPaginating || totalPages <= 1) return;

    let targetPage = newPage;
    if (targetPage > totalPages) targetPage = 1;
    if (targetPage < 1) targetPage = totalPages;
    
    if (targetPage === page) return;

    setIsPaginating(true);
    
    const isForward = (targetPage > page && !(page === 1 && targetPage === totalPages)) || (page === totalPages && targetPage === 1);
    const direction = isForward ? "left" : "right";
    
    setAnimationClass(direction === 'left' ? 'animate-fly-out-to-left' : 'animate-fly-out-to-right');

    setTimeout(() => {
      setPage(targetPage);
      setAnimationClass(direction === 'left' ? 'animate-fly-in-from-right' : 'animate-fly-in-from-left');
      
      setTimeout(() => {
        setAnimationClass('');
        setIsPaginating(false);
      }, 500);
    }, 300);
  };
  
  useEffect(() => {
    if (timerRef.current) {
      clearInterval(timerRef.current);
    }
    
    if (!isHovering && !isPaginating && !openItem && totalPages > 1) {
      timerRef.current = setInterval(() => {
        handlePageChange(page + 1);
      }, autoplayInterval);
    }
    
    return () => {
      if (timerRef.current) {
        clearInterval(timerRef.current);
      }
    };
  }, [page, isPaginating, isHovering, openItem, totalPages]);

  const renderContent = () => {
    if (isLoading) {
      return (
        <div className="space-y-4">
          <Skeleton className="h-32 w-full rounded-lg" />
          <Skeleton className="h-32 w-full rounded-lg" />
        </div>
      );
    }

    if (!news || news.length === 0) {
      return (
        <div className="text-center bg-card/50 p-8 rounded-lg">
          <p className="text-muted-foreground mb-4">No news articles have been published yet.</p>
          <p className="text-sm">
            Please log in and visit the <Link href="/admin/news" className="text-primary hover:underline font-semibold">News CMS</Link> to add the first articles.
          </p>
        </div>
      );
    }

    return (
      <>
        <div className={cn("relative", animationClass)}>
          <Accordion type="single" collapsible className="w-full space-y-4" onValueChange={setOpenItem} value={openItem}>
            {currentNews.map((item) => {
              const image = item.imageId ? PlaceHolderImages.find(p => p.id === item.imageId) : { imageUrl: item.imageUrl || '', description: item.title, imageHint: '' };
              return (
                <AccordionItem value={`item-${item.id}`} key={item.id} className="group bg-card border-none rounded-lg shadow-lg hover:shadow-primary/20 transition-shadow duration-300 overflow-hidden">
                  <div className="relative">
                    {image?.imageUrl && (
                      <div
                        className={cn(
                          "absolute z-20 rounded-md overflow-hidden transition-all duration-700 ease-in-out group-data-[state=closed]:cursor-pointer group-data-[state=closed]:hover:animate-pop-then-wiggle",
                          "group-data-[state=closed]:top-6 group-data-[state=closed]:left-6 group-data-[state=closed]:w-28 group-data-[state=closed]:aspect-[16/9] group-data-[state=closed]:shadow-lg",
                          "group-data-[state=open]:top-[7.5rem] group-data-[state=open]:left-6 group-data-[state=open]:w-[calc(100%-3rem)] group-data-[state=open]:aspect-video"
                        )}
                      >
                        <Image
                        src={image.imageUrl}
                        alt={image.description}
                        fill
                        className="object-cover"
                        data-ai-hint={image.imageHint}
                        />
                      </div>
                    )}
              
                    <AccordionPrimitive.Header className="relative flex z-10">
                        <AccordionPrimitive.Trigger className={cn(
                            "group/trigger text-left hover:no-underline w-full transition-all duration-700 ease-in-out py-6 pr-6",
                            "group-data-[state=closed]:pl-40",
                            "group-data-[state=open]:pl-6"
                        )}>
                            <div className="flex flex-row items-center w-full min-h-[3.9375rem]">
                                <div className="flex-1">
                                    <h3 className="font-headline text-lg sm:text-xl text-foreground transition-colors group-hover/trigger:text-primary group-data-[state=open]:text-primary" dangerouslySetInnerHTML={{ __html: item.title }} />
                                    <div className="text-xs font-mono text-muted-foreground mt-2 flex flex-wrap items-center gap-x-4 gap-y-1">
                                        <div className="flex items-center gap-1.5">
                                            <CalendarDays className="h-3.5 w-3.5" />
                                            <span>{format(new Date(item.date), 'PPP')}</span>
                                        </div>
                                        {item.location && (
                                            <div className="flex items-center gap-1.5">
                                                <MapPin className="h-3.5 w-3.5" />
                                                <span>{item.location}</span>
                                            </div>
                                        )}
                                        {item.author && (
                                            <div className="flex items-center gap-1.5">
                                                <User className="h-3.5 w-3.5" />
                                                <span>By <em>{item.author}</em></span>
                                            </div>
                                        )}
                                    </div>
                                </div>
                                <div className="pl-4">
                                    <ChevronUp className="h-4 w-4 shrink-0 transition-transform duration-200 group-data-[state=closed]:rotate-180" />
                                </div>
                            </div>
                        </AccordionPrimitive.Trigger>
                    </AccordionPrimitive.Header>
                  </div>
                  
                  <AccordionContent>
                      <div className="px-6 pb-6 pt-0">
                         <div className="pt-[calc(56.25%_+_1.5rem)]">
                            <div className="opacity-0 group-data-[state=open]:opacity-100 group-data-[state=open]:animate-fade-in-up group-data-[state=open]:[animation-delay:400ms]" style={{animationDuration: '1s', animationFillMode: 'forwards'}}>
                                <div className="border-t border-border/50 pt-4">
                                    <div 
                                        className="text-sm text-foreground/90 text-justify"
                                        dangerouslySetInnerHTML={{ __html: item.content }}
                                    />
                                </div>
                            </div>
                         </div>
                      </div>
                  </AccordionContent>
              </AccordionItem>
              );
            })}
          </Accordion>
        </div>

        {totalPages > 1 && (
          <div className="flex justify-center items-center mt-8 space-x-2">
            <Button
              variant="outline"
              size="icon"
              onClick={() => handlePageChange(page - 1)}
              disabled={isPaginating}
              className="rounded-full"
            >
              <ChevronLeft className="h-4 w-4" />
            </Button>
            {Array.from({ length: totalPages }).map((_, index) => (
              <Button
                key={index}
                variant={page === index + 1 ? "default" : "outline"}
                size="icon"
                onClick={() => handlePageChange(index + 1)}
                disabled={isPaginating}
                className="rounded-full"
              >
                {index + 1}
              </Button>
            ))}
            <Button
              variant="outline"
              size="icon"
              onClick={() => handlePageChange(page + 1)}
              disabled={isPaginating}
              className="rounded-full"
            >
              <ChevronRight className="h-4 w-4" />
            </Button>
          </div>
        )}
      </>
    );
  }

  return (
    <section 
      id="news" 
      className="py-20 sm:py-32 bg-card/20 overflow-hidden"
      onMouseEnter={() => setIsHovering(true)}
      onMouseLeave={() => setIsHovering(false)}
    >
      <div className="container mx-auto px-6 max-w-6xl">
        <div className="mb-12 text-center">
            <h2 className="text-3xl sm:text-4xl font-bold font-headline bg-gradient-to-r from-secondary to-primary to-[33%] bg-clip-text text-transparent mb-4 flex items-center justify-center gap-3">
                <Newspaper className="w-8 h-8 text-primary" />
                Latest News
            </h2>
            <p className="text-muted-foreground italic">The latest updates from the lab.</p>
        </div>
        
        {renderContent()}
      </div>
    </section>
  );
}
