// src/lib/components/Projects.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { fade, fly } from 'svelte/transition';
  import { pb } from '$lib/pocketbase';
  import { Lightbulb, Calendar, Landmark, Banknote, ExternalLink, Loader2 } from 'lucide-svelte';

  interface Project {
    id: string;
    title: string;
    description: string;
    start_date: string;
    end_date: string | null;
    status: string;
    funding_source: string;
    funding_source_url: string | null;
    budget: number;
    research_area: string;
  }

  let projects: Project[] = $state([]);
  let isLoading = $state(true);

  onMount(async () => {
    try {
      const data = await pb.collection('projects').getFullList({
        sort: '-start_date',
      });
        
      if (data) projects = data as unknown as Project[];
    } catch (e) {
      console.error("Error fetching projects:", e);
    } finally {
      isLoading = false;
    }
  });

</script>

<section id="projects" class="py-20 sm:py-32 bg-secondary/10 overflow-hidden">
  <div class="container mx-auto px-6">
    <div class="text-center mb-16">
      <h2 class="text-3xl sm:text-4xl font-bold font-slab bg-gradient-to-r from-secondary to-primary to-[33%] bg-clip-text text-transparent flex items-center justify-center gap-3">
        <Lightbulb class="w-8 h-8 text-primary" />
        Projects
      </h2>
    </div>
    
    <div class="max-w-6xl mx-auto">
      {#if isLoading}
        <div class="flex justify-center items-center py-20">
          <Loader2 class="w-8 h-8 animate-spin text-primary" />
        </div>
      {:else if projects.length === 0}
        <div class="flex flex-col items-center justify-center py-20 text-muted-foreground bg-card/50 rounded-xl border border-border">
          <Lightbulb class="w-12 h-12 mb-4 opacity-50" />
          <p class="text-lg font-medium">No projects found.</p>
        </div>
      {:else}
        <div class="grid md:grid-cols-1 lg:grid-cols-2 gap-8">
          {#each projects as project, i (project.id)}
            <div 
              in:fly={{ y: 20, duration: 600, delay: i * 100 }}
              class="flex flex-col bg-card rounded-xl shadow-lg hover:shadow-primary/20 transition-all duration-300 h-full border border-border/50"
            >
              <div class="p-6 sm:p-8 flex-grow flex flex-col">
                <h3 class="font-slab font-bold text-xl mb-6 text-foreground">{project.title}</h3>
                
                <div class="space-y-4 text-sm text-muted-foreground flex-grow">
                  {#if project.funding_source}
                    <div class="flex items-start gap-3">
                      <Landmark class="w-5 h-5 text-primary mt-0.5 shrink-0" />
                      <p class="flex-1">
                        <span class="font-semibold text-foreground/90">Funding provided by: </span>
                        {#if project.funding_source_url}
                          <a href={project.funding_source_url} target="_blank" rel="noopener noreferrer" class="group inline-flex flex-wrap items-center gap-1 hover:text-primary transition-colors">
                            <span>{project.funding_source}</span>
                            <ExternalLink class="w-3.5 h-3.5 opacity-50 group-hover:opacity-100 transition-opacity" />
                          </a>
                        {:else}
                          <span>{project.funding_source}</span>
                        {/if}
                      </p>
                    </div>
                  {/if}
                  
                  <div class="flex items-center gap-3">
                    <Calendar class="w-5 h-5 text-primary shrink-0" />
                    <p>
                      <span class="font-semibold text-foreground/90">Duration: </span>
                      {new Date(project.start_date).getFullYear()} - {project.end_date ? new Date(project.end_date).getFullYear() : 'Ongoing'}
                    </p>
                  </div>
                  
                  {#if project.budget > 0}
                    <div class="flex items-center gap-3">
                      <Banknote class="w-5 h-5 text-primary shrink-0" />
                      <p>
                        <span class="font-semibold text-foreground/90">Budget: </span>
                        {project.budget.toLocaleString('en-US')} PLN
                      </p>
                    </div>
                  {/if}
                </div>
              </div>
            </div>
          {/each}
        </div>
      {/if}
    </div>
  </div>
</section>

// src/components/sections/Projects.tsx
'use client';

import { useCollection } from '@/firebase/firestore/use-collection';
import { useFirestore, useMemoFirebase } from '@/firebase';
import { collection, query, orderBy } from 'firebase/firestore';
import { Project } from '@/lib/types';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Lightbulb, Calendar, Landmark, Banknote, ExternalLink } from "lucide-react";
import { AnimatedTitle } from "../layout/AnimatedTitle";
import { AnimatedWrapper } from "../layout/AnimatedWrapper";
import Link from "next/link";
import { Skeleton } from '@/components/ui/skeleton';

const ProjectSkeleton = () => (
    <Card className="flex flex-col bg-card shadow-lg h-full">
        <CardHeader>
            <Skeleton className="h-6 w-3/4" />
        </CardHeader>
        <CardContent className="space-y-4 text-sm">
            <div className="flex items-start gap-3">
                <Skeleton className="w-4 h-4 mt-1 rounded-full" />
                <Skeleton className="h-4 w-full" />
            </div>
            <div className="flex items-center gap-3">
                <Skeleton className="w-4 h-4 rounded-full" />
                <Skeleton className="h-4 w-1/2" />
            </div>
            <div className="flex items-center gap-3">
                <Skeleton className="w-4 h-4 rounded-full" />
                <Skeleton className="h-4 w-1/3" />
            </div>
        </CardContent>
    </Card>
)

export function Projects() {
  const firestore = useFirestore();

  const projectsQuery = useMemoFirebase(() => {
    return query(collection(firestore, 'projects'), orderBy('startDate', 'desc'));
  }, [firestore]);

  const { data: projects, isLoading } = useCollection<Project>(projectsQuery);

  return (
    <section id="projects" className="py-20 sm:py-32 bg-secondary/10">
      <div className="container mx-auto px-6">
        <AnimatedTitle className="text-3xl sm:text-4xl font-bold font-headline bg-gradient-to-r from-secondary to-primary to-[33%] bg-clip-text text-transparent mb-12 text-center">
          <div className="flex items-center justify-center gap-3">
            <Lightbulb className="w-8 h-8 text-primary" />
            Projects
          </div>
        </AnimatedTitle>
        
        <div className="max-w-6xl mx-auto">
          <div className="grid md:grid-cols-1 lg:grid-cols-2 gap-8">
            {isLoading && (
              <>
                <ProjectSkeleton />
                <ProjectSkeleton />
                <ProjectSkeleton />
                <ProjectSkeleton />
              </>
            )}
            {projects?.map((project, index) => (
              <AnimatedWrapper key={project.id} delay={100 + index * 100}>
                <Card className="flex flex-col bg-card shadow-lg hover:shadow-primary/20 transition-shadow duration-300 h-full">
                  <CardHeader>
                    <CardTitle className="font-headline text-lg">{project.title}</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4 text-sm text-muted-foreground flex-grow">
                    {project.fundingSource && (
                        <div className="flex items-start gap-3">
                        <Landmark className="w-4 h-4 text-primary mt-1 shrink-0" />
                        <p className="flex-1">
                            <span className="font-semibold text-foreground/90">Funding provided by: </span>
                            {project.fundingSourceUrl ? (
                                <Link href={project.fundingSourceUrl} target="_blank" rel="noopener noreferrer" className="group inline-flex items-center gap-1.5 hover:text-primary transition-colors">
                                <span>{project.fundingSource}</span>
                                <ExternalLink className="w-3.5 h-3.5 text-muted-foreground opacity-50 group-hover:opacity-100 transition-opacity" />
                                </Link>
                            ) : (
                                <span>{project.fundingSource}</span>
                            )}
                        </p>
                        </div>
                    )}
                    <div className="flex items-center gap-3">
                      <Calendar className="w-4 h-4 text-primary" />
                      <p>
                          <span className="font-semibold text-foreground/90">Duration: </span>
                          {new Date(project.startDate).getFullYear()} - {project.endDate ? new Date(project.endDate).getFullYear() : 'Ongoing'}
                      </p>
                    </div>
                    {project.budget > 0 && (
                        <div className="flex items-center gap-3">
                        <Banknote className="w-4 h-4 text-primary" />
                        <p>
                            <span className="font-semibold text-foreground/90">Budget: </span>
                            {project.budget.toLocaleString('en-US')} PLN
                        </p>
                        </div>
                    )}
                  </CardContent>
                </Card>
              </AnimatedWrapper>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
